CREATE TABLE Students
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR(1000) NOT NULL
)

CREATE TABLE Courses
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR (1000) NOT NULL,
	Department NVARCHAR(4) NOT NULL,
	Number NVARCHAR(4) NOT NULL,
	Section NVARCHAR(1) NOT NULL DEFAULT 'A',
	CONSTRAINT checkDepartment CHECK (Department = UPPER(Department)),
	CONSTRAINT checkSection CHECK (Section = UPPER(Section))
)

CREATE TABLE CoursesTaken
(
	Student UNIQUEIDENTIFIER NOT NULL,
	Course UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (Student) REFERENCES Students(Id),
	FOREIGN KEY (Course) REFERENCES Courses(Id)
)